import type { Config } from 'tailwindcss';

const config: Config = {
  content: [
    './pages/**/*.{js,ts,jsx,tsx,mdx}',
    './components/**/*.{js,ts,jsx,tsx,mdx}',
    './app/**/*.{js,ts,jsx,tsx,mdx}',
    './src/**/*.{js,ts,jsx,tsx,mdx}',
  ],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        // Design System Colors from stitch
        'outline-variant': '#abadae',
        error: '#b31b25',
        primary: '#006a35',
        'on-primary-fixed': '#004a23',
        'error-container': '#fb5151',
        'tertiary-container': '#00dcff',
        'on-error-container': '#570008',
        'on-surface-variant': '#595c5d',
        'primary-fixed-dim': '#5bef90',
        'surface-container-highest': '#dadddf',
        'on-secondary-fixed': '#004930',
        'on-secondary-fixed-variant': '#006946',
        'on-tertiary-fixed-variant': '#005361',
        'secondary-container': '#72fbbd',
        'surface-container-low': '#eff1f2',
        'secondary-fixed-dim': '#63ecaf',
        background: '#f5f6f7',
        'on-primary-fixed-variant': '#006a35',
        'on-background': '#2c2f30',
        'on-tertiary-container': '#004956',
        'inverse-primary': '#6bfe9c',
        'primary-dim': '#005c2d',
        secondary: '#006946',
        'inverse-on-surface': '#9b9d9e',
        'on-surface': '#2c2f30',
        'tertiary-fixed': '#00dcff',
        'on-secondary': '#c9ffdf',
        'surface-dim': '#d1d5d7',
        'surface-tint': '#006a35',
        surface: '#f5f6f7',
        'primary-container': '#6bfe9c',
        'surface-bright': '#f5f6f7',
        outline: '#757778',
        'primary-fixed': '#6bfe9c',
        'surface-variant': '#dadddf',
        'surface-container': '#e6e8ea',
        'inverse-surface': '#0c0f10',
        'on-primary': '#cdffd4',
        tertiary: '#006576',
        'on-tertiary-fixed': '#00333d',
        'secondary-dim': '#005c3d',
        'on-tertiary': '#ddf7ff',
        'tertiary-fixed-dim': '#00cdee',
        'surface-container-lowest': '#ffffff',
        'tertiary-dim': '#005867',
        'secondary-fixed': '#72fbbd',
        'on-primary-container': '#005f2f',
        'on-error': '#ffefee',
        'on-secondary-container': '#005e3e',
        'surface-container-high': '#e0e3e4',
        'error-dim': '#9f0519',
      },
      borderRadius: {
        DEFAULT: '1rem',
        lg: '2rem',
        xl: '3rem',
        '2xl': '3rem',
        full: '9999px',
      },
      fontFamily: {
        headline: ['var(--font-manrope)', 'Manrope', 'sans-serif'],
        body: ['var(--font-manrope)', 'Manrope', 'sans-serif'],
        label: ['var(--font-manrope)', 'Manrope', 'sans-serif'],
        sans: ['var(--font-manrope)', 'Manrope', 'sans-serif'],
      },
    },
  },
  plugins: [require('@tailwindcss/forms')],
};

export default config;
