/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/hansim/summary/batch": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 다중 소환사 한심 summary 조회 (최대 5명)
         * @description 여러 소환사의 큐별 승패, 랭크 정보, 스트릭, 챔피언 통계를 한 번에 조회합니다. 비로그인/로그인 모두 사용 가능합니다.
         */
        post: operations["getBatchSummary"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/google": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 구글 소셜 로그인/회원가입
         * @description Google access token을 검증하고 JWT를 발급합니다. 최초 요청 시 자동 회원가입됩니다.
         */
        post: operations["googleLogin"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["health"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/hansim/summary/{riotId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 단일 소환사 한심 summary 조회
         * @description Riot ID 기준으로 지정 기간의 큐별 승패 및 한심 지수를 조회합니다.
         */
        get: operations["getSummary"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/withdraw": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * 회원탈퇴
         * @description 현재 로그인된 회원을 soft delete 처리합니다. 탈퇴 후 기존 토큰은 즉시 무효화됩니다.
         */
        delete: operations["withdraw"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** @description 다중 소환사 한심 지수 조회 요청 */
        BatchSummaryRequest: {
            /**
             * @description 조회할 Riot ID 목록. '이름#태그' 또는 '이름-태그' 형식 모두 허용. 최소 1명 최대 5명
             * @example [
             *       "페이커#KR1",
             *       "카나비#KR1"
             *     ]
             */
            riotIds: string[];
            /**
             * Format: date
             * @description 조회 시작일 (yyyy-MM-dd). 미입력 시 오늘(KST)
             * @example 2026-04-01
             */
            startDate?: string;
            /**
             * Format: date
             * @description 조회 종료일 (yyyy-MM-dd). 미입력 시 오늘(KST). 최대 7일 범위
             * @example 2026-04-10
             */
            endDate?: string;
        };
        /** @description 다중 소환사 한심 지수 조회 응답 */
        BatchSummaryResponse: {
            /** @description 조회 기간 (Unix epoch 기준) */
            period: components["schemas"]["Period"];
            /** @description 조회 기간 문자열 (KST). 예: '2026-04-01 (수) 오전 6시 ~ 2026-04-02 (목) 오전 6시 (KST)' */
            periodStr: string;
            /** @description 소환사별 통계 목록 */
            players: components["schemas"]["Player"][];
        };
        /** @description 챔피언별 통계 */
        Champion: {
            /**
             * Format: int32
             * @description 챔피언 ID
             * @example 1
             */
            championId: number;
            /**
             * @description 챔피언 이름
             * @example Ahri
             */
            championName: string;
            /**
             * Format: int32
             * @description 게임 수
             * @example 5
             */
            games: number;
            /**
             * Format: int32
             * @description 승리 수
             * @example 3
             */
            wins: number;
            /**
             * @description 승률 (%)
             * @example 60
             */
            winRate: string;
            /**
             * @description 평균 KDA
             * @example 4.2
             */
            kda: string;
            /** @description 가장 많이 플레이한 포지션 (TOP/JUNGLE/MID/BOTTOM/UTILITY). 포지션 정보 없으면 null */
            topPosition?: string;
        };
        /** @description HLS 부분 점수 */
        HlsDetail: {
            /**
             * Format: int32
             * @description A. 볼륨 (0~30): 총 플레이 분 + 판수
             * @example 24
             */
            volume?: number;
            /**
             * Format: int32
             * @description B. 결과 (0~20): 패배/서렌/KDA 기반
             * @example 16
             */
            result?: number;
            /**
             * Format: int32
             * @description C. 심야 (0~15): KST 00~06시 누적 분
             * @example 10
             */
            lateNight?: number;
            /**
             * Format: int32
             * @description D. 주말 (0~10): 토/일 누적 분
             * @example 0
             */
            weekend?: number;
            /**
             * Format: int32
             * @description E. 세션 (0~10): 최장 연속 플레이
             * @example 8
             */
            session?: number;
            /**
             * Format: int32
             * @description F. 연패 (0~10): 최대 연속 패배
             * @example 10
             */
            losingStreak?: number;
            /**
             * Format: int32
             * @description G. 분노재큐 (0~5): 패배 후 5분 내 재입장
             * @example 4
             */
            tilt?: number;
        };
        /** @description 한심지수 (NINE_TO_SIX 기준) */
        HlsResponse: {
            /**
             * Format: int32
             * @description 최종 HLS (0~100)
             * @example 72
             */
            total?: number;
            /** @description 부분 점수 상세 */
            detail?: components["schemas"]["HlsDetail"];
        };
        /** @description 멀티킬 합산 */
        MultiKills: {
            /**
             * Format: int32
             * @description 더블킬 횟수
             * @example 5
             */
            doubles: number;
            /**
             * Format: int32
             * @description 트리플킬 횟수
             * @example 2
             */
            triples: number;
            /**
             * Format: int32
             * @description 쿼드라킬 횟수
             * @example 1
             */
            quadras: number;
            /**
             * Format: int32
             * @description 펜타킬 횟수
             * @example 0
             */
            pentas: number;
        };
        /** @description 조회 기간 (ISO-8601) */
        Period: {
            /**
             * Format: date-time
             * @description 시작 시각 (ISO-8601)
             * @example 2026-04-01T21:00:00Z
             */
            start: string;
            /**
             * Format: date-time
             * @description 종료 시각 (ISO-8601)
             * @example 2026-04-02T21:00:00Z
             */
            end: string;
        };
        /** @description 소환사 통계 */
        Player: {
            /**
             * @description Riot ID (gameName#tagLine)
             * @example 페이커#KR1
             */
            riotId: string;
            /**
             * Format: int32
             * @description 프로필 아이콘 ID
             * @example 4567
             */
            profileIconId: number;
            /**
             * Format: int64
             * @description 소환사 레벨
             * @example 500
             */
            summonerLevel: number;
            /** @description 솔로 랭크 정보. 배치 미완료 시 null */
            soloRank?: components["schemas"]["RankInfo"];
            /** @description 자유 랭크 정보. 배치 미완료 시 null */
            flexRank?: components["schemas"]["RankInfo"];
            /** @description 조회 기간 내 큐별 통계 */
            queues: components["schemas"]["Queues"];
            /** @description 현재 연승/연패 스트릭 */
            streak: components["schemas"]["StreakInfo"];
            /** @description 조회 기간 내 챔피언별 통계 (게임 수 내림차순) */
            topChampions: components["schemas"]["Champion"][];
            /**
             * Format: int32
             * @description 전체 큐 합산 총 플레이 시간 (초)
             * @example 10800
             */
            totalPlaySeconds: number;
            /** @description 한심지수 (NINE_TO_SIX 기준) */
            hls: components["schemas"]["HlsResponse"];
        };
        /** @description 단일 큐 통계 */
        QueueInfo: {
            /**
             * Format: int32
             * @description 총 게임 수
             * @example 10
             */
            games: number;
            /**
             * Format: int32
             * @description 승리 수
             * @example 6
             */
            win: number;
            /**
             * Format: int32
             * @description 패배 수
             * @example 4
             */
            lose: number;
            /**
             * @description 승률 (%)
             * @example 60
             */
            winRate: string;
            /**
             * @description 평균 KDA (소수점 1자리)
             * @example 3.5
             */
            kda: string;
            /**
             * Format: int32
             * @description 큐 총 플레이 시간 (초)
             * @example 7200
             */
            totalPlaySeconds: number;
            /**
             * Format: int32
             * @description 판당 평균 게임 시간 (초)
             * @example 1800
             */
            avgGameDurationSeconds: number;
            /**
             * @description 분당 평균 CS (소수점 1자리)
             * @example 6.5
             */
            avgCsPerMin: string;
            /**
             * Format: int32
             * @description 게임당 평균 챔피언 피해량
             * @example 18500
             */
            avgDamage: number;
            /**
             * @description 게임당 평균 비전 점수 (소수점 1자리)
             * @example 21.3
             */
            avgVisionScore: string;
            /** @description 멀티킬 합산 횟수 */
            multiKills: components["schemas"]["MultiKills"];
        };
        /** @description 큐별 통계 */
        Queues: {
            /** @description 일반 게임. 해당 기간 게임 없으면 null */
            normal?: components["schemas"]["QueueInfo"];
            /** @description 솔로 랭크. 해당 기간 게임 없으면 null */
            solo?: components["schemas"]["QueueInfo"];
            /** @description 자유 랭크. 해당 기간 게임 없으면 null */
            flex?: components["schemas"]["QueueInfo"];
            /** @description 칼바람 나락. 해당 기간 게임 없으면 null */
            aram?: components["schemas"]["QueueInfo"];
        };
        /** @description 랭크 정보 */
        RankInfo: {
            /**
             * @description 티어 (IRON~CHALLENGER)
             * @example DIAMOND
             */
            tier: string;
            /**
             * @description 단계 (I~IV)
             * @example II
             */
            rank: string;
            /**
             * Format: int32
             * @description 리그 포인트
             * @example 75
             */
            lp: number;
            /**
             * Format: int32
             * @description 시즌 총 승리 수
             * @example 120
             */
            wins: number;
            /**
             * Format: int32
             * @description 시즌 총 패배 수
             * @example 100
             */
            losses: number;
            /**
             * @description 시즌 승률 (%)
             * @example 54.5
             */
            winRate: string;
        };
        /** @description 현재 연승/연패 스트릭 */
        StreakInfo: {
            /**
             * @description 스트릭 유형 (WIN / LOSE / NONE)
             * @example WIN
             */
            type: string;
            /**
             * Format: int32
             * @description 연속 횟수
             * @example 3
             */
            count: number;
        };
        /** @description 구글 소셜 로그인 요청 */
        GoogleLoginRequestBody: {
            /**
             * @description 프론트엔드 Google Sign-In SDK에서 발급받은 ID token (JWT 형식, eyJ로 시작)
             * @example eyJhbGciOiJSUzI1NiIsImtpZCI6...
             */
            googleToken: string;
        };
        /** @description 인증 토큰 응답 */
        AuthResponse: {
            /** @description JWT access token. 유효기간 7일 */
            accessToken: string;
        };
        /** @description 한심 summary 조회 쿼리 파라미터 */
        SummaryRequestQuery: {
            /**
             * Format: date
             * @description 조회 시작일. 미입력 시 오늘(KST)로 설정
             * @example 2026-04-01
             */
            startDate?: string;
            /**
             * Format: date
             * @description 조회 종료일. 미입력 시 오늘(KST)로 설정. startDate 이후여야 하며 최대 7일 범위
             * @example 2026-04-10
             */
            endDate?: string;
        };
        /** @description 한심 summary 조회 응답 */
        SummaryResponse: {
            /** @description 조회 기간 (Unix epoch ms 기준) */
            period: components["schemas"]["Period"];
            /**
             * @description 조회 기간 문자열 (KST 기준). 예: '2026-04-01 (수) 오전 6시 ~ 2026-04-02 (목) 오전 6시 (KST)'
             * @example 2026-04-01 (수) 오전 6시 ~ 2026-04-02 (목) 오전 6시 (KST)
             */
            periodStr: string;
            /** @description 플레이어별 큐 통계 목록 */
            players: components["schemas"]["Player"][];
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    getBatchSummary: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["BatchSummaryRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["BatchSummaryResponse"];
                };
            };
        };
    };
    googleLogin: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["GoogleLoginRequestBody"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["AuthResponse"];
                };
            };
        };
    };
    health: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": string;
                };
            };
        };
    };
    getSummary: {
        parameters: {
            query: {
                query: components["schemas"]["SummaryRequestQuery"];
            };
            header?: never;
            path: {
                /**
                 * @description Riot ID. 반드시 '이름-태그' 슬러그 형식 (예: 페이커-KR1). '#' 구분자는 허용하지 않음
                 * @example 페이커-KR1
                 */
                riotId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["SummaryResponse"];
                };
            };
        };
    };
    withdraw: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No Content */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
}
